name: Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-unix:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
          lfs: true
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.203" # SDK Version to use.
      - name: Build
        run: dotnet build src
